name: "Terraform-Destroy"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Install Terraform"
      uses: hashicorp/setup-terraform@v3

    - name: "Terraform init"
      working-directory: ./src
      run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_KEY }}" -backend-config="region=${{ secrets.AWS_BUCKET_REGION }}"

    - name: "Terraform Destroy Command"
      working-directory: ./src
      run: terraform destroy --auto-approve
