name: "Terraform-Techack"

on:
  push:
    branches: ["main"]
    paths: ["src/**"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Configure AWS Credentials"
      # uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        # AWS Region, e.g. us-east-2
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
